version: "3"

services:
  app:
    build: .
    ports:
      - 8000:8000
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=VerySecure
    ports:
      - 5432:5432
    volumes:
      - .volumes/postgres:/var/lib/postgresql/data
